import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#dfe0e0",
        "surface-container-high": "#dce9ff",
        "tertiary-container": "#3e4c5c",
        "secondary-fixed": "#e2e2e2",
        "on-tertiary-fixed": "#0e1d2b",
        "on-surface-variant": "#444653",
        "primary": "#00288e",
        "on-secondary-fixed": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b8c4ff",
        "surface-container-highest": "#d3e4fe",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#adbccf",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#b9c8db",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#3a4858",
        "tertiary": "#273545",
        "inverse-primary": "#b8c4ff",
        "outline": "#757684",
        "on-primary-fixed": "#001453",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed": "#d5e4f8",
        "primary-container": "#1e40af",
        "secondary-fixed-dim": "#c6c6c7",
        "on-secondary-container": "#616363",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed-variant": "#454747",
        "on-primary-container": "#a8b8ff",
        "surface-container": "#e5eeff",
        "surface": "#f8f9ff",
        "surface-tint": "#3755c3",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary": "#5d5f5f",
        "primary-fixed": "#dde1ff",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "error": "#ba1a1a",
        "inverse-surface": "#213145",
        "surface-container-low": "#eff4ff",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed-variant": "#173bab",
        "outline-variant": "#c4c5d5",
        "on-surface": "#0b1c30",
        "background": "#f8f9ff",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Manrope", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "headline-md": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "max-width-content": "480px",
        xs: "4px",
        "margin-mobile": "16px",
        gutter: "16px",
        md: "16px",
        sm: "8px",
        xl: "32px",
        "margin-desktop": "auto",
        lg: "24px",
        base: "4px",
      },
      maxWidth: {
        "content": "480px",
      },
    },
  },
  plugins: [],
};

export default config;
